---
language: c
dist: xenial
# We need sudo for some of the Docker commands.
sudo: required

# Provide a list of OSes we want to use for testing.
env:
  - distro: python
    version: 2
  - distro: ubuntu
    version: 16.04
  - distro: debian
    version: latest
#  - distro: base/archlinux
#    version: latest

# Tell Travis to start Docker when it brings up an environment.
services:
  - docker

before_install:
  # Pull the image from Docker Hub for the OS under test.
  - ./bin/install_dependencies.sh
  - docker pull ${distro}:${version}

script:
  # Start the container from the image and perform tests.
  - DOCKER_IMAGE="${distro}:${version}" ./cm.sh test

notifications:
  # Notify Ansible Galaxy when a role builds successfully.


