---
- name: locale | Create en_US.UTF-8 locale
  locale_gen: name=en_US.UTF-8 state=present

- name: locale | Create de_DE.UTF-8 locale
  locale_gen: name=de_DE.UTF-8 state=present

- name: locale | write locale configration
  become: yes
  template:
    src: locale.j2
    dest: /etc/default/locale
    force: yes
    owner: root
    group: root
    mode: 'u=rw,go=r'
  register: locale_config

- name: locale | apply locale configration
  become: yes
  command: /usr/sbin/dpkg-reconfigure -f noninteractive locales
  when: locale_config.changed and ansible_os_family == 'Debian'
