---
# tasks file for os---
#
- name: Role - package_install
  debug:
    msg: "package_install"
    verbosity: 1
- name: show parameter package_list
  debug:
    msg: "{{ package_list }}"

- import_tasks: Debian.yml
  when: ansible_os_family == 'Debian'
- import_tasks: Archlinux.yml
  when: ansible_os_family == 'Archlinux'
