---
- name: user | Create Users
  user:
    createhome: yes
    name: "{{ item.name }}"
    comment: "{{ item.comment }}"
    groups: "{{ item.groups }}"
    shell: "{{ item.shell }}"
    state: "{{ item.state }}"
  become: true
  with_items:
    - "{{ pre_puppet_users }}"
        #      - { name: 'usera', comment: 'usera', groups: 'sudo,docker', shell: '/bin/bash', state: present }
        #      - { name: 'userb', comment: 'userb', groups: 'docker', shell: '/bin/bash', state: present }

- name: user | Populate SSH Keys
  authorized_key:
    key: "{{ lookup('file',item) }}"
    user: "{{ item | basename }}"
    manage_dir: ye
  with_fileglob:
    - "ssh_keys/*"
