---
- hosts: local
  become: "yes"

  vars_files:
    - "{{ playbook_dir }}/variables.yml"

  roles:
    - os_upgrade    # up-to-date operating system
    - role: package_install
      package_list: "{{ package_install.package_list }}"
    - role: ntp_client
      ntp_server: "{{ ntp_client.ntp_server }}"

#  roles:
#    - role: package_install
#      package_list: "{{ package_install.package_list_debian }}"
#      when: ansible_os_family == 'Debian'

#    - common       # List of essential packages
#    - home         # prepare and configure home directory
#    - docker       # install and configure docker
#    - user         # create user
#    - c            # c and tools
#    - python       # python and tools
#    - golang       # golang and tools

# https://github.com/briangershon/linux-desktop-ansible
# - include: ../../linux-desktop-private/playbook.yml
