---
- hosts: local
  connection: local
  remote_user: root
  become_method: sudo

  vars_files:
    - variables.yml

  roles:
    - common       # List of essential packages
    - home         # prepare and configure home directory
    - docker       # install and configure docker
#    - c            # c and tools
    - python       # python and tools
    - golang       # golang and tools

