---
- hosts: local

  vars_files:
    - "{{ playbook_dir }}/variables.yml"
    - ["~/files/secrets/aws_s3_backup.yml", "{{ playbook_dir }}/roles/backup/vars/main.yml"]

  roles:
    - role: backup
      aws_s3_backup_encryption_passphase: "{{ aws_s3_backup_encryption_passphrase }}"
      backup_files: "{{ backup.backup_files }}"
