---
#
# role "package_install" settings
#

# packages to install
package_install:
  package_list:
    - bash-completion
    - bzip2
    - curl
    - fail2ban
    - git
    - gzip
    - htop
    - lsof
    - ntp
    - python
    - python-virtualenv
    - rkhunter
    - rsync
    - screen
    - strace
    - tar
    - tree
    - unzip
    - vim
    - wget
    - zip 



#
# role "ntp_client" settings
#
ntp_client:
  ntp_server: ntp1.ptb.de



#
# role "test" settings
test:
  base_dir: "{{ playbook_dir }}/.."

  

# user settings
#user:
#  user_name: "{{ ansible_ssh_user }}"
#  user_home: /home/{{ user }}
#  dotfiles: "{{ user_home }}/files/dotfiles"
