---
#
# generic stuff
#
generic:
  nothing: "by now"


#
# role "package_install" settings
#

# packages to install
package_install:
  package_list:
    - bash-completion
    - bzip2
    - curl
    - fail2ban
    - git
    - gnupg
    - gzip
    - htop
    - lsof
    - ntp
    - python
    - python-virtualenv
    - rkhunter
    - rsync
    - screen
    - strace
    - tar
    - tree
    - tmux
    - unzip
    - vim
    - wget
    - xdotool
    - zip
    - zsh
  package_list_archlinux:
    - keepass
  package_list_debian:
    - python-apt


#
# role "ntp_client" settings
#
ntp_client:
  ntp_server: ntp1.ptb.de


#
# role "test" settings
#
test:
  base_dir: "{{ playbook_dir }}/.."


#
# role "backup" settings
#
backup:
  backup_files:
    - ~/.ssh
    - ~/.vimrc
    - ~/.zshrc
    - ~/files
    - ~/Documents
    - ~/Pictures


#
# role "dotfiles" settings
#
dotfiles:
  dotfiles_files:
    - .gitconfig
    - .gitexcludes
    - .gitignore
    - .noserc
    - .screenrc
    - .shellrc.aliases
    - .shellrc.env
    - .shellrc.functions
    - .shellrc.golang
    - .shellrc.host.wb-t500
    - .shellrc.load
    - .shellrc.prompt
    - .shellrc.ssh
    - .vimrc
    - .zshrc


# user settings
# user:
#   user_name: "{{ ansible_ssh_user }}"
#   user_home: /home/{{ user }}
#   dotfiles: "{{ user_home }}/files/dotfiles"
